# Generated by Django 5.1 on 2026-05-07 18:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('address', 'Address')], max_length=20)),
                ('guidance', models.TextField(blank=True, null=True)),
                ('hint', models.CharField(blank=True, max_length=255, null=True)),
                ('options', models.TextField(blank=True, help_text='Semicolon-delimited options for radio and checkbox questions', null=True)),
                ('answer_type', models.CharField(blank=True, choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regime',
            fields=[
                ('regime_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('regime_name', models.CharField(max_length=255)),
                ('dept_id', models.CharField(blank=True, max_length=100, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'regime_name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'core_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('lapsed', 'Lapsed')], default='draft', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='The citizen this case belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
                ('regime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='core.regime')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('schedule_name', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('regime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.regime')),
            ],
            options={
                'ordering': ['display_order', 'schedule_name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=255)),
                ('section_type', models.IntegerField(choices=[(0, 'Standard'), (1, 'Table')], default=0)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('section_guidance', models.TextField(blank=True, null=True)),
                ('column_question_ids', models.TextField(blank=True, help_text='Semicolon-delimited question IDs defining table column display order', null=True)),
                ('totals_question_ids', models.TextField(blank=True, help_text='Semicolon-delimited question IDs whose numeric values are totalled', null=True)),
                ('regime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_sections', to='core.regime')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.schedule')),
            ],
            options={
                'ordering': ['display_order', 'section_name'],
            },
        ),
        migrations.CreateModel(
            name='AnswerTableHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(default=list, help_text='Full table snapshot at the point of displacement')),
                ('confirmed_at', models.DateTimeField(help_text='The timestamp at which this snapshot was displaced')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_history_authored', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_answer_history', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_answer_history', to='core.case')),
                ('regime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.regime')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section')),
            ],
            options={
                'ordering': ['-confirmed_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='not_started', max_length=20)),
                ('regime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.regime')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'regime', 'schedule'), name='unique_schedule_status')],
            },
        ),
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.TextField(blank=True, help_text='Answer that triggers this route; null means unconditional', null=True)),
                ('order_in_section', models.PositiveIntegerField(default=0)),
                ('current_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='core.question')),
                ('next_question', models.ForeignKey(blank=True, help_text='Null means END — citizen proceeds to check-your-answers', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='core.question')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='core.section')),
            ],
            options={
                'ordering': ['order_in_section'],
                'constraints': [models.UniqueConstraint(fields=('section', 'current_question', 'answer_value'), name='unique_routing_rule')],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_delegate', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(help_text='The individual granted access', on_delete=django.db.models.deletion.CASCADE, related_name='permissions_as_actor', to=settings.AUTH_USER_MODEL)),
                ('granted_by', models.ForeignKey(blank=True, help_text='Null means granted directly by the user; otherwise the delegating actor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The citizen whose data is at stake', on_delete=django.db.models.deletion.CASCADE, related_name='permissions_as_subject', to=settings.AUTH_USER_MODEL)),
                ('regime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.regime')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.section')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('actor', 'user', 'regime', 'section'), name='unique_permission')],
            },
        ),
        migrations.CreateModel(
            name='AnswerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(default=list, help_text='List of row dicts, one per table row entered by the citizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_answers_provided', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_answers', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_answers', to='core.case')),
                ('regime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.regime')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'regime', 'case', 'section'), name='unique_table_answer')],
            },
        ),
        migrations.CreateModel(
            name='AnswerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(blank=True, help_text='Null means this answer was removed by a routing change', null=True)),
                ('confirmed_at', models.DateTimeField(help_text='The timestamp at which this value was displaced')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_authored', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_history', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_history', to='core.case')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
                ('regime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.regime')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section')),
            ],
            options={
                'ordering': ['-confirmed_at'],
                'indexes': [models.Index(fields=['user', 'regime', 'case', 'section', 'confirmed_at'], name='idx_anshist_section_lookup'), models.Index(fields=['user', 'question', 'confirmed_at'], name='idx_anshist_question_lookup')],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(help_text='Scalar value or list (for checkbox answers)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(help_text='The individual who provided this answer (may differ from user)', on_delete=django.db.models.deletion.CASCADE, related_name='answers_provided', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The citizen whose answer this is', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.case')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.question')),
                ('regime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.regime')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.section')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'regime', 'case', 'question', 'updated_at'], name='idx_answer_case_lookup'), models.Index(fields=['user', 'question', 'updated_at'], name='idx_answer_prepop_lookup')],
                'constraints': [models.UniqueConstraint(fields=('user', 'regime', 'case', 'question', 'actor'), name='unique_answer')],
            },
        ),
        migrations.CreateModel(
            name='SectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='not_started', max_length=20)),
                ('regime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.regime')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'regime', 'section'), name='unique_section_status')],
            },
        ),
    ]
