# Generated by Django 5.1 on 2026-05-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.IntegerField(choices=[(0, 'Standard'), (1, 'Table'), (2, 'Table with routing')], default=0),
        ),
    ]
