# Generated by Django 5.1 on 2026-05-14 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_questionset_questionsetmember_alter_routing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('address', 'Address'), ('date', 'Date')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionsetmember',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_memberships', to='core.question'),
        ),
        migrations.AlterField(
            model_name='routing',
            name='current_node',
            field=models.CharField(help_text='Q-prefixed question ID or S-prefixed set ID for this screen', max_length=100),
        ),
    ]
