# Generated by Django 5.1 on 2026-05-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_department_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='copied_from',
            field=models.CharField(blank=True, help_text='Audit: section_id this section was copied from, if any', max_length=100, null=True),
        ),
    ]
