# Generated by Django 5.1 on 2026-05-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_section_copied_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_platform',
            field=models.BooleanField(default=False, help_text='True for META/wizard questions. Excluded from the shared question bank views.'),
        ),
    ]
