# Generated by Django 5.1 on 2026-05-17 12:58

from django.db import migrations


def mark_platform(apps, schema_editor):
    Question = apps.get_model('core', 'Question')
    Question.objects.filter(
        question_id__in=[f'Q{i}' for i in range(33, 60)]
    ).update(is_platform=True)


def unmark_platform(apps, schema_editor):
    Question = apps.get_model('core', 'Question')
    Question.objects.filter(
        question_id__in=[f'Q{i}' for i in range(33, 60)]
    ).update(is_platform=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_is_platform_to_question'),
    ]

    operations = [
        migrations.RunPython(mark_platform, unmark_platform),
    ]
