# Generated by Django 5.1 on 2026-05-18 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mark_platform_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='regime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.regime'),
        ),
    ]
