# Generated by Django 5.1 on 2026-05-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_schedule_regime_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='reference',
            field=models.CharField(blank=True, help_text='Assigned reference number (e.g. IHT-XXXXXXXXX). Null until assigned or if submission is unverified.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('address', 'Address'), ('date', 'Date'), ('personal_name', 'Personal name')], max_length=20),
        ),
    ]
