# Generated by Django 5.1 on 2026-05-28 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_case_reference'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='permission',
            name='unique_permission',
        ),
        migrations.AddField(
            model_name='permission',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.case'),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(fields=('actor', 'user', 'regime', 'section', 'case'), name='unique_permission'),
        ),
    ]
