# Generated by Django 5.1 on 2026-06-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_permission_case_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='routing',
            name='comparator',
            field=models.CharField(blank=True, choices=[('=', 'Equal to'), ('<', 'Less than'), ('<=', 'Less than or equal to'), ('>', 'Greater than'), ('>=', 'Greater than or equal to')], help_text='Scalar comparator for numeric routing; leave blank for equality matching on answer_value', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='routing',
            name='threshold_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Threshold for scalar comparison; leave blank for standard answer_value matching', max_digits=15, null=True),
        ),
    ]
