# Generated by Django 5.1 on 2026-06-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_routing_comparator_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='show_confirmation',
            field=models.BooleanField(default=True, help_text='When True (default) the citizen sees a check-your-answers page before answers are saved. Uncheck for navigation-only sections that should auto-save and return to the regime home immediately.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('address', 'Address'), ('date', 'Date'), ('personal_name', 'Personal name'), ('compound', 'Compound')], max_length=20),
        ),
    ]
