# Generated by Django 5.1 on 2026-07-01 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_routing_condition_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('radio', 'Radio'), ('radio_inline', 'Radio inline'), ('checkbox', 'Checkbox'), ('address', 'Address'), ('date', 'Date'), ('personal_name', 'Personal name'), ('compound', 'Compound')], max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='display_question_ids',
            field=models.TextField(blank=True, help_text='Semicolon-delimited question IDs to display as table columns.\nFor flat tables (type 1): defines add-form columns and display order.\nFor routed tables (type 2): declares which routed questions appear as\nsummary columns. Routing defines the full row journey.', null=True),
        ),
        migrations.CreateModel(
            name='SectionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100)),
                ('node_type', models.CharField(choices=[('Q', 'Question'), ('S', 'Set')], max_length=1)),
                ('added_order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.section')),
            ],
            options={
                'ordering': ['added_order'],
                'unique_together': {('section', 'node_id')},
            },
        ),
    ]
