# Generated by Django 5.1 on 2026-08-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_routing_order_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='routing',
            name='alternate_condition_id',
            field=models.CharField(blank=True, help_text='Optional slot-2 question ID. If set, slot-2 tests the answer to this question rather than the current node. Must have been answered earlier in the journey.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='routing',
            name='comparator_1',
            field=models.CharField(blank=True, choices=[('=', 'Equal to'), ('<', 'Less than'), ('<=', 'Less than or equal to'), ('>', 'Greater than'), ('>=', 'Greater than or equal to')], help_text='Slot-1 comparator. "=" for text equality; numeric ops for numeric questions.', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='routing',
            name='comparator_2',
            field=models.CharField(blank=True, choices=[('=', 'Equal to'), ('<', 'Less than'), ('<=', 'Less than or equal to'), ('>', 'Greater than'), ('>=', 'Greater than or equal to')], help_text='Slot-2 comparator. Only evaluated when alternate_condition_id is set.', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='routing',
            name='test_value_1',
            field=models.TextField(blank=True, help_text='Slot-1 value to test against. Null means unconditional (no slot-1 test).', null=True),
        ),
        migrations.AddField(
            model_name='routing',
            name='test_value_2',
            field=models.TextField(blank=True, help_text='Slot-2 value to test against. Only evaluated when alternate_condition_id is set.', null=True),
        ),
    ]
