# Generated by Django 5.1 on 2026-08-16 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_routing_migrate_compound_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionQuestionGuidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guidance_override', models.TextField(blank=True, null=True)),
                ('hint_override', models.CharField(blank=True, max_length=255, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_overrides', to='core.question')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_guidance_overrides', to='core.section')),
            ],
            options={
                'unique_together': {('section', 'question')},
            },
        ),
    ]
