# Generated by Django 5.1 on 2026-08-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_sectionquestionguidance'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='set_guidance',
            field=models.TextField(blank=True, null=True),
        ),
    ]
