# Generated by Django 5.1 on 2026-08-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_set_guidance_to_questionset'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Maximum numeric value allowed (number questions).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='max_date',
            field=models.DateField(blank=True, help_text='Latest date allowed (ISO-formatted text answers).', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='max_length',
            field=models.IntegerField(blank=True, help_text='Maximum number of characters allowed (text/textarea questions).', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='min',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Minimum numeric value allowed (number questions).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='min_date',
            field=models.DateField(blank=True, help_text='Earliest date allowed (ISO-formatted text answers).', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='no_future_date',
            field=models.BooleanField(default=False, help_text='If True, reject answers that are after today (ISO-formatted text answers).'),
        ),
        migrations.AddField(
            model_name='question',
            name='regex',
            field=models.CharField(blank=True, help_text='Regular expression the answer must match (text questions).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=True, help_text='If False, a blank submission is accepted for this question.'),
        ),
    ]
