# Generated by Django 5.1 on 2026-06-16 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_add_section_show_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='IHTReckoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion', models.CharField(max_length=20)),
                ('question_text', models.TextField(blank=True, default='')),
                ('threshold', models.IntegerField(blank=True, null=True)),
                ('answer', models.CharField(blank=True, default='', max_length=10)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iht_reckoner', to='core.case')),
            ],
            options={
                'db_table': 'dept_hmrc_ihtreckoner',
            },
        ),
    ]
